package com.duopei.springmvc.model.testtransction;

import java.util.Date;

public class Account {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taccount.CUST_NO
     *
     * @mbggenerated
     */
    private String custNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taccount.AMT
     *
     * @mbggenerated
     */
    private Double amt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taccount.INSERT_ID
     *
     * @mbggenerated
     */
    private String insertId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taccount.INSERT_DATE
     *
     * @mbggenerated
     */
    private Date insertDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taccount.MODIFY_ID
     *
     * @mbggenerated
     */
    private String modifyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taccount.MODIFY_DATE
     *
     * @mbggenerated
     */
    private Date modifyDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taccount.CUST_NO
     *
     * @return the value of taccount.CUST_NO
     *
     * @mbggenerated
     */
    public String getCustNo() {
        return custNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taccount.CUST_NO
     *
     * @param custNo the value for taccount.CUST_NO
     *
     * @mbggenerated
     */
    public void setCustNo(String custNo) {
        this.custNo = custNo == null ? null : custNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taccount.AMT
     *
     * @return the value of taccount.AMT
     *
     * @mbggenerated
     */
    public Double getAmt() {
        return amt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taccount.AMT
     *
     * @param amt the value for taccount.AMT
     *
     * @mbggenerated
     */
    public void setAmt(Double amt) {
        this.amt = amt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taccount.INSERT_ID
     *
     * @return the value of taccount.INSERT_ID
     *
     * @mbggenerated
     */
    public String getInsertId() {
        return insertId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taccount.INSERT_ID
     *
     * @param insertId the value for taccount.INSERT_ID
     *
     * @mbggenerated
     */
    public void setInsertId(String insertId) {
        this.insertId = insertId == null ? null : insertId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taccount.INSERT_DATE
     *
     * @return the value of taccount.INSERT_DATE
     *
     * @mbggenerated
     */
    public Date getInsertDate() {
        return insertDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taccount.INSERT_DATE
     *
     * @param insertDate the value for taccount.INSERT_DATE
     *
     * @mbggenerated
     */
    public void setInsertDate(Date insertDate) {
        this.insertDate = insertDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taccount.MODIFY_ID
     *
     * @return the value of taccount.MODIFY_ID
     *
     * @mbggenerated
     */
    public String getModifyId() {
        return modifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taccount.MODIFY_ID
     *
     * @param modifyId the value for taccount.MODIFY_ID
     *
     * @mbggenerated
     */
    public void setModifyId(String modifyId) {
        this.modifyId = modifyId == null ? null : modifyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taccount.MODIFY_DATE
     *
     * @return the value of taccount.MODIFY_DATE
     *
     * @mbggenerated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taccount.MODIFY_DATE
     *
     * @param modifyDate the value for taccount.MODIFY_DATE
     *
     * @mbggenerated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }
}