package com.duopei.springmvc.model.testtransction;

public class ItemPriceKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column titemprice.item_code
     *
     * @mbggenerated
     */
    private String itemCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column titemprice.unit_code
     *
     * @mbggenerated
     */
    private String unitCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column titemprice.item_code
     *
     * @return the value of titemprice.item_code
     *
     * @mbggenerated
     */
    public String getItemCode() {
        return itemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column titemprice.item_code
     *
     * @param itemCode the value for titemprice.item_code
     *
     * @mbggenerated
     */
    public void setItemCode(String itemCode) {
        this.itemCode = itemCode == null ? null : itemCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column titemprice.unit_code
     *
     * @return the value of titemprice.unit_code
     *
     * @mbggenerated
     */
    public String getUnitCode() {
        return unitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column titemprice.unit_code
     *
     * @param unitCode the value for titemprice.unit_code
     *
     * @mbggenerated
     */
    public void setUnitCode(String unitCode) {
        this.unitCode = unitCode == null ? null : unitCode.trim();
    }
}