package com.duopei.springmvc.model.testtransction;

public class ItemPrice extends ItemPriceKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column titemprice.sale_price
     *
     * @mbggenerated
     */
    private Double salePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column titemprice.sale_cost
     *
     * @mbggenerated
     */
    private Double saleCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column titemprice.sale_vat
     *
     * @mbggenerated
     */
    private Double saleVat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column titemprice.sale_rate
     *
     * @mbggenerated
     */
    private Double saleRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column titemprice.buy_price
     *
     * @mbggenerated
     */
    private Double buyPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column titemprice.buy_cost
     *
     * @mbggenerated
     */
    private Double buyCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column titemprice.buy_vat
     *
     * @mbggenerated
     */
    private Double buyVat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column titemprice.buy_rate
     *
     * @mbggenerated
     */
    private Double buyRate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column titemprice.sale_price
     *
     * @return the value of titemprice.sale_price
     *
     * @mbggenerated
     */
    public Double getSalePrice() {
        return salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column titemprice.sale_price
     *
     * @param salePrice the value for titemprice.sale_price
     *
     * @mbggenerated
     */
    public void setSalePrice(Double salePrice) {
        this.salePrice = salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column titemprice.sale_cost
     *
     * @return the value of titemprice.sale_cost
     *
     * @mbggenerated
     */
    public Double getSaleCost() {
        return saleCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column titemprice.sale_cost
     *
     * @param saleCost the value for titemprice.sale_cost
     *
     * @mbggenerated
     */
    public void setSaleCost(Double saleCost) {
        this.saleCost = saleCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column titemprice.sale_vat
     *
     * @return the value of titemprice.sale_vat
     *
     * @mbggenerated
     */
    public Double getSaleVat() {
        return saleVat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column titemprice.sale_vat
     *
     * @param saleVat the value for titemprice.sale_vat
     *
     * @mbggenerated
     */
    public void setSaleVat(Double saleVat) {
        this.saleVat = saleVat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column titemprice.sale_rate
     *
     * @return the value of titemprice.sale_rate
     *
     * @mbggenerated
     */
    public Double getSaleRate() {
        return saleRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column titemprice.sale_rate
     *
     * @param saleRate the value for titemprice.sale_rate
     *
     * @mbggenerated
     */
    public void setSaleRate(Double saleRate) {
        this.saleRate = saleRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column titemprice.buy_price
     *
     * @return the value of titemprice.buy_price
     *
     * @mbggenerated
     */
    public Double getBuyPrice() {
        return buyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column titemprice.buy_price
     *
     * @param buyPrice the value for titemprice.buy_price
     *
     * @mbggenerated
     */
    public void setBuyPrice(Double buyPrice) {
        this.buyPrice = buyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column titemprice.buy_cost
     *
     * @return the value of titemprice.buy_cost
     *
     * @mbggenerated
     */
    public Double getBuyCost() {
        return buyCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column titemprice.buy_cost
     *
     * @param buyCost the value for titemprice.buy_cost
     *
     * @mbggenerated
     */
    public void setBuyCost(Double buyCost) {
        this.buyCost = buyCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column titemprice.buy_vat
     *
     * @return the value of titemprice.buy_vat
     *
     * @mbggenerated
     */
    public Double getBuyVat() {
        return buyVat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column titemprice.buy_vat
     *
     * @param buyVat the value for titemprice.buy_vat
     *
     * @mbggenerated
     */
    public void setBuyVat(Double buyVat) {
        this.buyVat = buyVat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column titemprice.buy_rate
     *
     * @return the value of titemprice.buy_rate
     *
     * @mbggenerated
     */
    public Double getBuyRate() {
        return buyRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column titemprice.buy_rate
     *
     * @param buyRate the value for titemprice.buy_rate
     *
     * @mbggenerated
     */
    public void setBuyRate(Double buyRate) {
        this.buyRate = buyRate;
    }
}