package com.duopei.springmvc.model.testtransction;

import java.util.Date;

public class Stock extends StockKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tstock.qty
     *
     * @mbggenerated
     */
    private Integer qty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tstock.oper_grogram
     *
     * @mbggenerated
     */
    private String operGrogram;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tstock.insert_id
     *
     * @mbggenerated
     */
    private String insertId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tstock.insert_date
     *
     * @mbggenerated
     */
    private Date insertDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tstock.modify_id
     *
     * @mbggenerated
     */
    private String modifyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tstock.modify_date
     *
     * @mbggenerated
     */
    private Date modifyDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tstock.qty
     *
     * @return the value of tstock.qty
     *
     * @mbggenerated
     */
    public Integer getQty() {
        return qty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tstock.qty
     *
     * @param qty the value for tstock.qty
     *
     * @mbggenerated
     */
    public void setQty(Integer qty) {
        this.qty = qty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tstock.oper_grogram
     *
     * @return the value of tstock.oper_grogram
     *
     * @mbggenerated
     */
    public String getOperGrogram() {
        return operGrogram;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tstock.oper_grogram
     *
     * @param operGrogram the value for tstock.oper_grogram
     *
     * @mbggenerated
     */
    public void setOperGrogram(String operGrogram) {
        this.operGrogram = operGrogram == null ? null : operGrogram.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tstock.insert_id
     *
     * @return the value of tstock.insert_id
     *
     * @mbggenerated
     */
    public String getInsertId() {
        return insertId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tstock.insert_id
     *
     * @param insertId the value for tstock.insert_id
     *
     * @mbggenerated
     */
    public void setInsertId(String insertId) {
        this.insertId = insertId == null ? null : insertId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tstock.insert_date
     *
     * @return the value of tstock.insert_date
     *
     * @mbggenerated
     */
    public Date getInsertDate() {
        return insertDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tstock.insert_date
     *
     * @param insertDate the value for tstock.insert_date
     *
     * @mbggenerated
     */
    public void setInsertDate(Date insertDate) {
        this.insertDate = insertDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tstock.modify_id
     *
     * @return the value of tstock.modify_id
     *
     * @mbggenerated
     */
    public String getModifyId() {
        return modifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tstock.modify_id
     *
     * @param modifyId the value for tstock.modify_id
     *
     * @mbggenerated
     */
    public void setModifyId(String modifyId) {
        this.modifyId = modifyId == null ? null : modifyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tstock.modify_date
     *
     * @return the value of tstock.modify_date
     *
     * @mbggenerated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tstock.modify_date
     *
     * @param modifyDate the value for tstock.modify_date
     *
     * @mbggenerated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }
}