package com.duopei.springmvc.model.testtransction;

public class StockKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tstock.wh_code
     *
     * @mbggenerated
     */
    private String whCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tstock.item_code
     *
     * @mbggenerated
     */
    private String itemCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tstock.unit_code
     *
     * @mbggenerated
     */
    private String unitCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tstock.wh_code
     *
     * @return the value of tstock.wh_code
     *
     * @mbggenerated
     */
    public String getWhCode() {
        return whCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tstock.wh_code
     *
     * @param whCode the value for tstock.wh_code
     *
     * @mbggenerated
     */
    public void setWhCode(String whCode) {
        this.whCode = whCode == null ? null : whCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tstock.item_code
     *
     * @return the value of tstock.item_code
     *
     * @mbggenerated
     */
    public String getItemCode() {
        return itemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tstock.item_code
     *
     * @param itemCode the value for tstock.item_code
     *
     * @mbggenerated
     */
    public void setItemCode(String itemCode) {
        this.itemCode = itemCode == null ? null : itemCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tstock.unit_code
     *
     * @return the value of tstock.unit_code
     *
     * @mbggenerated
     */
    public String getUnitCode() {
        return unitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tstock.unit_code
     *
     * @param unitCode the value for tstock.unit_code
     *
     * @mbggenerated
     */
    public void setUnitCode(String unitCode) {
        this.unitCode = unitCode == null ? null : unitCode.trim();
    }
}