package com.duopei.springmvc.model.example;

import com.duopei.springmvc.model.base.Base;

import java.sql.Date;
import java.util.List;

public class Example extends Base  {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column example.EXP_ID
     *
     * @mbggenerated
     */
    private Integer expId;

    private List<String> interests;

    private String jobType;
    private String marryType;

    @Override
    public String toString() {
        return "Example{" +
                "expId=" + expId +
                ", interests=" + interests +
                ", jobType='" + jobType + '\'' +
                ", marryType='" + marryType + '\'' +
                ", expName='" + expName + '\'' +
                ", expSex='" + expSex + '\'' +
                ", expDate=" + expDate +
                ", expYn='" + expYn + '\'' +
                '}';
    }

    public String getMarryType() {
        return marryType;
    }

    public void setMarryType(String marryType) {
        this.marryType = marryType;
    }

    public String getJobType() {
        return jobType;
    }

    public void setJobType(String jobType) {
        this.jobType = jobType;
    }

    public List<String> getInterests() {
        return interests;
    }

    public void setInterests(List<String> interests) {
        this.interests = interests;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column example.EXP_NAME
     *
     * @mbggenerated
     */
    private String expName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column example.EXP_SEX
     *
     * @mbggenerated
     */
    private String expSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column example.EXP_DATE
     *
     * @mbggenerated
     */
    private Date expDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column example.EXP_YN
     *
     * @mbggenerated
     */
    private String expYn;


    public Integer getExpId() {
        return expId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column example.EXP_ID
     *
     * @param expId the value for example.EXP_ID
     *
     * @mbggenerated
     */
    public void setExpId(Integer expId) {
        this.expId = expId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column example.EXP_NAME
     *
     * @return the value of example.EXP_NAME
     *
     * @mbggenerated
     */
    public String getExpName() {
        return expName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column example.EXP_NAME
     *
     * @param expName the value for example.EXP_NAME
     *
     * @mbggenerated
     */
    public void setExpName(String expName) {
        this.expName = expName == null ? null : expName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column example.EXP_SEX
     *
     * @return the value of example.EXP_SEX
     *
     * @mbggenerated
     */
    public String getExpSex() {
        return expSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column example.EXP_SEX
     *
     * @param expSex the value for example.EXP_SEX
     *
     * @mbggenerated
     */
    public void setExpSex(String expSex) {
        this.expSex = expSex == null ? null : expSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column example.EXP_DATE
     *
     * @return the value of example.EXP_DATE
     *
     * @mbggenerated
     */
    public Date getExpDate() {
        return expDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column example.EXP_DATE
     *
     * @param expDate the value for example.EXP_DATE
     *
     * @mbggenerated
     */
    public void setExpDate(Date expDate) {
        this.expDate = expDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column example.EXP_YN
     *
     * @return the value of example.EXP_YN
     *
     * @mbggenerated
     */
    public String getExpYn() {
        return expYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column example.EXP_YN
     *
     * @param expYn the value for example.EXP_YN
     *
     * @mbggenerated
     */
    public void setExpYn(String expYn) {
        this.expYn = expYn == null ? null : expYn.trim();
    }

}