 package com.duopei.springmvc.model.user;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tusers.NO
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tusers.USER_CODE
     *
     * @mbggenerated
     */
    private String userCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tusers.USER_TEL
     *
     * @mbggenerated
     */
    private String userTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tusers.USER_EMAIL
     *
     * @mbggenerated
     */
    private String userEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tusers.USER_PWD
     *
     * @mbggenerated
     */
    private String userPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tusers.USER_NAME
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tusers.USER_STATUS
     *
     * @mbggenerated
     */
    private Integer userStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tusers.COMMONS
     *
     * @mbggenerated
     */
    private String commons;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tusers.LAST_LOGIN_TIME
     *
     * @mbggenerated
     */
    private Date lastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tusers.LAST_UPDATE_PWD_DATE
     *
     * @mbggenerated
     */
    private Date lastUpdatePwdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tusers.INSERT_ID
     *
     * @mbggenerated
     */
    private String insertId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tusers.INSERT_DATE
     *
     * @mbggenerated
     */
    private Date insertDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tusers.MODIFY_ID
     *
     * @mbggenerated
     */
    private String modifyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tusers.MODIFY_DATE
     *
     * @mbggenerated
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tusers.LAST_VERSION
     *
     * @mbggenerated
     */
    private Long lastVersion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tusers.userId
     *
     * @return the value of tusers.userId
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tusers.userId
     *
     * @param userId the value for tusers.userId
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tusers.USER_CODE
     *
     * @return the value of tusers.USER_CODE
     *
     * @mbggenerated
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tusers.USER_CODE
     *
     * @param userCode the value for tusers.USER_CODE
     *
     * @mbggenerated
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode == null ? null : userCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tusers.USER_TEL
     *
     * @return the value of tusers.USER_TEL
     *
     * @mbggenerated
     */
    public String getUserTel() {
        return userTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tusers.USER_TEL
     *
     * @param userTel the value for tusers.USER_TEL
     *
     * @mbggenerated
     */
    public void setUserTel(String userTel) {
        this.userTel = userTel == null ? null : userTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tusers.USER_EMAIL
     *
     * @return the value of tusers.USER_EMAIL
     *
     * @mbggenerated
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tusers.USER_EMAIL
     *
     * @param userEmail the value for tusers.USER_EMAIL
     *
     * @mbggenerated
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail == null ? null : userEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tusers.USER_PWD
     *
     * @return the value of tusers.USER_PWD
     *
     * @mbggenerated
     */
    public String getUserPwd() {
        return userPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tusers.USER_PWD
     *
     * @param userPwd the value for tusers.USER_PWD
     *
     * @mbggenerated
     */
    public void setUserPwd(String userPwd) {
        this.userPwd = userPwd == null ? null : userPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tusers.USER_NAME
     *
     * @return the value of tusers.USER_NAME
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tusers.USER_NAME
     *
     * @param userName the value for tusers.USER_NAME
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tusers.USER_STATUS
     *
     * @return the value of tusers.USER_STATUS
     *
     * @mbggenerated
     */
    public Integer getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tusers.USER_STATUS
     *
     * @param userStatus the value for tusers.USER_STATUS
     *
     * @mbggenerated
     */
    public void setUserStatus(Integer userStatus) {
        this.userStatus = userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tusers.COMMONS
     *
     * @return the value of tusers.COMMONS
     *
     * @mbggenerated
     */
    public String getCommons() {
        return commons;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tusers.COMMONS
     *
     * @param commons the value for tusers.COMMONS
     *
     * @mbggenerated
     */
    public void setCommons(String commons) {
        this.commons = commons == null ? null : commons.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tusers.LAST_LOGIN_TIME
     *
     * @return the value of tusers.LAST_LOGIN_TIME
     *
     * @mbggenerated
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tusers.LAST_LOGIN_TIME
     *
     * @param lastLoginTime the value for tusers.LAST_LOGIN_TIME
     *
     * @mbggenerated
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tusers.LAST_UPDATE_PWD_DATE
     *
     * @return the value of tusers.LAST_UPDATE_PWD_DATE
     *
     * @mbggenerated
     */
    public Date getLastUpdatePwdDate() {
        return lastUpdatePwdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tusers.LAST_UPDATE_PWD_DATE
     *
     * @param lastUpdatePwdDate the value for tusers.LAST_UPDATE_PWD_DATE
     *
     * @mbggenerated
     */
    public void setLastUpdatePwdDate(Date lastUpdatePwdDate) {
        this.lastUpdatePwdDate = lastUpdatePwdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tusers.INSERT_ID
     *
     * @return the value of tusers.INSERT_ID
     *
     * @mbggenerated
     */
    public String getInsertId() {
        return insertId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tusers.INSERT_ID
     *
     * @param insertId the value for tusers.INSERT_ID
     *
     * @mbggenerated
     */
    public void setInsertId(String insertId) {
        this.insertId = insertId == null ? null : insertId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tusers.INSERT_DATE
     *
     * @return the value of tusers.INSERT_DATE
     *
     * @mbggenerated
     */
    public Date getInsertDate() {
        return insertDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tusers.INSERT_DATE
     *
     * @param insertDate the value for tusers.INSERT_DATE
     *
     * @mbggenerated
     */
    public void setInsertDate(Date insertDate) {
        this.insertDate = insertDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tusers.MODIFY_ID
     *
     * @return the value of tusers.MODIFY_ID
     *
     * @mbggenerated
     */
    public String getModifyId() {
        return modifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tusers.MODIFY_ID
     *
     * @param modifyId the value for tusers.MODIFY_ID
     *
     * @mbggenerated
     */
    public void setModifyId(String modifyId) {
        this.modifyId = modifyId == null ? null : modifyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tusers.MODIFY_DATE
     *
     * @return the value of tusers.MODIFY_DATE
     *
     * @mbggenerated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tusers.MODIFY_DATE
     *
     * @param modifyDate the value for tusers.MODIFY_DATE
     *
     * @mbggenerated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tusers.LAST_VERSION
     *
     * @return the value of tusers.LAST_VERSION
     *
     * @mbggenerated
     */
    public Long getLastVersion() {
        return lastVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tusers.LAST_VERSION
     *
     * @param lastVersion the value for tusers.LAST_VERSION
     *
     * @mbggenerated
     */
    public void setLastVersion(Long lastVersion) {
        this.lastVersion = lastVersion;
    }
}