package com.duopei.springmvc.model.base;

import java.util.Date;

public class Code {


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcode.CODE_LGROUP
     *
     * @mbggenerated
     */
    private String codeLgroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcode.CODE_MGROUP
     *
     * @mbggenerated
     */
    private String codeMgroup;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcode.CODE_LGROUP
     *
     * @return the value of tcode.CODE_LGROUP
     *
     * @mbggenerated
     */
    public String getCodeLgroup() {
        return codeLgroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcode.CODE_LGROUP
     *
     * @param codeLgroup the value for tcode.CODE_LGROUP
     *
     * @mbggenerated
     */
    public void setCodeLgroup(String codeLgroup) {
        this.codeLgroup = codeLgroup == null ? null : codeLgroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcode.CODE_MGROUP
     *
     * @return the value of tcode.CODE_MGROUP
     *
     * @mbggenerated
     */
    public String getCodeMgroup() {
        return codeMgroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcode.CODE_MGROUP
     *
     * @param codeMgroup the value for tcode.CODE_MGROUP
     *
     * @mbggenerated
     */
    public void setCodeMgroup(String codeMgroup) {
        this.codeMgroup = codeMgroup == null ? null : codeMgroup.trim();
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcode.CODE_NAME
     *
     * @mbggenerated
     */
    private String codeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcode.CODE_GROUP
     *
     * @mbggenerated
     */
    private String codeGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcode.CODE_TYPE
     *
     * @mbggenerated
     */
    private String codeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcode.CODE_SORT
     *
     * @mbggenerated
     */
    private Integer codeSort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcode.USE_YN
     *
     * @mbggenerated
     */
    private String useYn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcode.INSERT_ID
     *
     * @mbggenerated
     */
    private String insertId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcode.INSERT_DATE
     *
     * @mbggenerated
     */
    private Date insertDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcode.CODE_TAG02
     *
     * @mbggenerated
     */
    private String codeTag02;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcode.CODE_TAG03
     *
     * @mbggenerated
     */
    private String codeTag03;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcode.CODE_TAG04
     *
     * @mbggenerated
     */
    private String codeTag04;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcode.CODE_TAG05
     *
     * @mbggenerated
     */
    private String codeTag05;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcode.CODE_TAG06
     *
     * @mbggenerated
     */
    private String codeTag06;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcode.CODE_TAG07
     *
     * @mbggenerated
     */
    private String codeTag07;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcode.CODE_TAG08
     *
     * @mbggenerated
     */
    private String codeTag08;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcode.CODE_TAG09
     *
     * @mbggenerated
     */
    private String codeTag09;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcode.CODE_TAG10
     *
     * @mbggenerated
     */
    private String codeTag10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcode.CODE_TAG11
     *
     * @mbggenerated
     */
    private String codeTag11;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcode.CODE_TAG22
     *
     * @mbggenerated
     */
    private String codeTag22;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcode.CODE_TAG13
     *
     * @mbggenerated
     */
    private String codeTag13;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcode.CODE_TAG14
     *
     * @mbggenerated
     */
    private String codeTag14;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcode.CODE_TAG15
     *
     * @mbggenerated
     */
    private String codeTag15;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcode.CODE_TAG16
     *
     * @mbggenerated
     */
    private String codeTag16;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcode.CODE_TAG17
     *
     * @mbggenerated
     */
    private String codeTag17;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcode.CODE_TAG18
     *
     * @mbggenerated
     */
    private String codeTag18;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcode.CODE_TAG19
     *
     * @mbggenerated
     */
    private String codeTag19;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcode.MODIFY_ID
     *
     * @mbggenerated
     */
    private String modifyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcode.MODIFY_DATE
     *
     * @mbggenerated
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcode.CODE_TAG
     *
     * @mbggenerated
     */
    private String codeTag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcode.CODE_TAG01
     *
     * @mbggenerated
     */
    private String codeTag01;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcode.CODE_NAME
     *
     * @return the value of tcode.CODE_NAME
     *
     * @mbggenerated
     */
    public String getCodeName() {
        return codeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcode.CODE_NAME
     *
     * @param codeName the value for tcode.CODE_NAME
     *
     * @mbggenerated
     */
    public void setCodeName(String codeName) {
        this.codeName = codeName == null ? null : codeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcode.CODE_GROUP
     *
     * @return the value of tcode.CODE_GROUP
     *
     * @mbggenerated
     */
    public String getCodeGroup() {
        return codeGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcode.CODE_GROUP
     *
     * @param codeGroup the value for tcode.CODE_GROUP
     *
     * @mbggenerated
     */
    public void setCodeGroup(String codeGroup) {
        this.codeGroup = codeGroup == null ? null : codeGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcode.CODE_TYPE
     *
     * @return the value of tcode.CODE_TYPE
     *
     * @mbggenerated
     */
    public String getCodeType() {
        return codeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcode.CODE_TYPE
     *
     * @param codeType the value for tcode.CODE_TYPE
     *
     * @mbggenerated
     */
    public void setCodeType(String codeType) {
        this.codeType = codeType == null ? null : codeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcode.CODE_SORT
     *
     * @return the value of tcode.CODE_SORT
     *
     * @mbggenerated
     */
    public Integer getCodeSort() {
        return codeSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcode.CODE_SORT
     *
     * @param codeSort the value for tcode.CODE_SORT
     *
     * @mbggenerated
     */
    public void setCodeSort(Integer codeSort) {
        this.codeSort = codeSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcode.USE_YN
     *
     * @return the value of tcode.USE_YN
     *
     * @mbggenerated
     */
    public String getUseYn() {
        return useYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcode.USE_YN
     *
     * @param useYn the value for tcode.USE_YN
     *
     * @mbggenerated
     */
    public void setUseYn(String useYn) {
        this.useYn = useYn == null ? null : useYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcode.INSERT_ID
     *
     * @return the value of tcode.INSERT_ID
     *
     * @mbggenerated
     */
    public String getInsertId() {
        return insertId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcode.INSERT_ID
     *
     * @param insertId the value for tcode.INSERT_ID
     *
     * @mbggenerated
     */
    public void setInsertId(String insertId) {
        this.insertId = insertId == null ? null : insertId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcode.INSERT_DATE
     *
     * @return the value of tcode.INSERT_DATE
     *
     * @mbggenerated
     */
    public Date getInsertDate() {
        return insertDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcode.INSERT_DATE
     *
     * @param insertDate the value for tcode.INSERT_DATE
     *
     * @mbggenerated
     */
    public void setInsertDate(Date insertDate) {
        this.insertDate = insertDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcode.CODE_TAG02
     *
     * @return the value of tcode.CODE_TAG02
     *
     * @mbggenerated
     */
    public String getCodeTag02() {
        return codeTag02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcode.CODE_TAG02
     *
     * @param codeTag02 the value for tcode.CODE_TAG02
     *
     * @mbggenerated
     */
    public void setCodeTag02(String codeTag02) {
        this.codeTag02 = codeTag02 == null ? null : codeTag02.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcode.CODE_TAG03
     *
     * @return the value of tcode.CODE_TAG03
     *
     * @mbggenerated
     */
    public String getCodeTag03() {
        return codeTag03;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcode.CODE_TAG03
     *
     * @param codeTag03 the value for tcode.CODE_TAG03
     *
     * @mbggenerated
     */
    public void setCodeTag03(String codeTag03) {
        this.codeTag03 = codeTag03 == null ? null : codeTag03.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcode.CODE_TAG04
     *
     * @return the value of tcode.CODE_TAG04
     *
     * @mbggenerated
     */
    public String getCodeTag04() {
        return codeTag04;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcode.CODE_TAG04
     *
     * @param codeTag04 the value for tcode.CODE_TAG04
     *
     * @mbggenerated
     */
    public void setCodeTag04(String codeTag04) {
        this.codeTag04 = codeTag04 == null ? null : codeTag04.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcode.CODE_TAG05
     *
     * @return the value of tcode.CODE_TAG05
     *
     * @mbggenerated
     */
    public String getCodeTag05() {
        return codeTag05;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcode.CODE_TAG05
     *
     * @param codeTag05 the value for tcode.CODE_TAG05
     *
     * @mbggenerated
     */
    public void setCodeTag05(String codeTag05) {
        this.codeTag05 = codeTag05 == null ? null : codeTag05.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcode.CODE_TAG06
     *
     * @return the value of tcode.CODE_TAG06
     *
     * @mbggenerated
     */
    public String getCodeTag06() {
        return codeTag06;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcode.CODE_TAG06
     *
     * @param codeTag06 the value for tcode.CODE_TAG06
     *
     * @mbggenerated
     */
    public void setCodeTag06(String codeTag06) {
        this.codeTag06 = codeTag06 == null ? null : codeTag06.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcode.CODE_TAG07
     *
     * @return the value of tcode.CODE_TAG07
     *
     * @mbggenerated
     */
    public String getCodeTag07() {
        return codeTag07;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcode.CODE_TAG07
     *
     * @param codeTag07 the value for tcode.CODE_TAG07
     *
     * @mbggenerated
     */
    public void setCodeTag07(String codeTag07) {
        this.codeTag07 = codeTag07 == null ? null : codeTag07.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcode.CODE_TAG08
     *
     * @return the value of tcode.CODE_TAG08
     *
     * @mbggenerated
     */
    public String getCodeTag08() {
        return codeTag08;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcode.CODE_TAG08
     *
     * @param codeTag08 the value for tcode.CODE_TAG08
     *
     * @mbggenerated
     */
    public void setCodeTag08(String codeTag08) {
        this.codeTag08 = codeTag08 == null ? null : codeTag08.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcode.CODE_TAG09
     *
     * @return the value of tcode.CODE_TAG09
     *
     * @mbggenerated
     */
    public String getCodeTag09() {
        return codeTag09;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcode.CODE_TAG09
     *
     * @param codeTag09 the value for tcode.CODE_TAG09
     *
     * @mbggenerated
     */
    public void setCodeTag09(String codeTag09) {
        this.codeTag09 = codeTag09 == null ? null : codeTag09.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcode.CODE_TAG10
     *
     * @return the value of tcode.CODE_TAG10
     *
     * @mbggenerated
     */
    public String getCodeTag10() {
        return codeTag10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcode.CODE_TAG10
     *
     * @param codeTag10 the value for tcode.CODE_TAG10
     *
     * @mbggenerated
     */
    public void setCodeTag10(String codeTag10) {
        this.codeTag10 = codeTag10 == null ? null : codeTag10.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcode.CODE_TAG11
     *
     * @return the value of tcode.CODE_TAG11
     *
     * @mbggenerated
     */
    public String getCodeTag11() {
        return codeTag11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcode.CODE_TAG11
     *
     * @param codeTag11 the value for tcode.CODE_TAG11
     *
     * @mbggenerated
     */
    public void setCodeTag11(String codeTag11) {
        this.codeTag11 = codeTag11 == null ? null : codeTag11.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcode.CODE_TAG22
     *
     * @return the value of tcode.CODE_TAG22
     *
     * @mbggenerated
     */
    public String getCodeTag22() {
        return codeTag22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcode.CODE_TAG22
     *
     * @param codeTag22 the value for tcode.CODE_TAG22
     *
     * @mbggenerated
     */
    public void setCodeTag22(String codeTag22) {
        this.codeTag22 = codeTag22 == null ? null : codeTag22.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcode.CODE_TAG13
     *
     * @return the value of tcode.CODE_TAG13
     *
     * @mbggenerated
     */
    public String getCodeTag13() {
        return codeTag13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcode.CODE_TAG13
     *
     * @param codeTag13 the value for tcode.CODE_TAG13
     *
     * @mbggenerated
     */
    public void setCodeTag13(String codeTag13) {
        this.codeTag13 = codeTag13 == null ? null : codeTag13.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcode.CODE_TAG14
     *
     * @return the value of tcode.CODE_TAG14
     *
     * @mbggenerated
     */
    public String getCodeTag14() {
        return codeTag14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcode.CODE_TAG14
     *
     * @param codeTag14 the value for tcode.CODE_TAG14
     *
     * @mbggenerated
     */
    public void setCodeTag14(String codeTag14) {
        this.codeTag14 = codeTag14 == null ? null : codeTag14.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcode.CODE_TAG15
     *
     * @return the value of tcode.CODE_TAG15
     *
     * @mbggenerated
     */
    public String getCodeTag15() {
        return codeTag15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcode.CODE_TAG15
     *
     * @param codeTag15 the value for tcode.CODE_TAG15
     *
     * @mbggenerated
     */
    public void setCodeTag15(String codeTag15) {
        this.codeTag15 = codeTag15 == null ? null : codeTag15.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcode.CODE_TAG16
     *
     * @return the value of tcode.CODE_TAG16
     *
     * @mbggenerated
     */
    public String getCodeTag16() {
        return codeTag16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcode.CODE_TAG16
     *
     * @param codeTag16 the value for tcode.CODE_TAG16
     *
     * @mbggenerated
     */
    public void setCodeTag16(String codeTag16) {
        this.codeTag16 = codeTag16 == null ? null : codeTag16.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcode.CODE_TAG17
     *
     * @return the value of tcode.CODE_TAG17
     *
     * @mbggenerated
     */
    public String getCodeTag17() {
        return codeTag17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcode.CODE_TAG17
     *
     * @param codeTag17 the value for tcode.CODE_TAG17
     *
     * @mbggenerated
     */
    public void setCodeTag17(String codeTag17) {
        this.codeTag17 = codeTag17 == null ? null : codeTag17.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcode.CODE_TAG18
     *
     * @return the value of tcode.CODE_TAG18
     *
     * @mbggenerated
     */
    public String getCodeTag18() {
        return codeTag18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcode.CODE_TAG18
     *
     * @param codeTag18 the value for tcode.CODE_TAG18
     *
     * @mbggenerated
     */
    public void setCodeTag18(String codeTag18) {
        this.codeTag18 = codeTag18 == null ? null : codeTag18.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcode.CODE_TAG19
     *
     * @return the value of tcode.CODE_TAG19
     *
     * @mbggenerated
     */
    public String getCodeTag19() {
        return codeTag19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcode.CODE_TAG19
     *
     * @param codeTag19 the value for tcode.CODE_TAG19
     *
     * @mbggenerated
     */
    public void setCodeTag19(String codeTag19) {
        this.codeTag19 = codeTag19 == null ? null : codeTag19.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcode.MODIFY_ID
     *
     * @return the value of tcode.MODIFY_ID
     *
     * @mbggenerated
     */
    public String getModifyId() {
        return modifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcode.MODIFY_ID
     *
     * @param modifyId the value for tcode.MODIFY_ID
     *
     * @mbggenerated
     */
    public void setModifyId(String modifyId) {
        this.modifyId = modifyId == null ? null : modifyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcode.MODIFY_DATE
     *
     * @return the value of tcode.MODIFY_DATE
     *
     * @mbggenerated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcode.MODIFY_DATE
     *
     * @param modifyDate the value for tcode.MODIFY_DATE
     *
     * @mbggenerated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcode.CODE_TAG
     *
     * @return the value of tcode.CODE_TAG
     *
     * @mbggenerated
     */
    public String getCodeTag() {
        return codeTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcode.CODE_TAG
     *
     * @param codeTag the value for tcode.CODE_TAG
     *
     * @mbggenerated
     */
    public void setCodeTag(String codeTag) {
        this.codeTag = codeTag == null ? null : codeTag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcode.CODE_TAG01
     *
     * @return the value of tcode.CODE_TAG01
     *
     * @mbggenerated
     */
    public String getCodeTag01() {
        return codeTag01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcode.CODE_TAG01
     *
     * @param codeTag01 the value for tcode.CODE_TAG01
     *
     * @mbggenerated
     */
    public void setCodeTag01(String codeTag01) {
        this.codeTag01 = codeTag01 == null ? null : codeTag01.trim();
    }
}