package com.duopei.springmvc.model.menu;

import java.util.List;

public class Menu {

    public List<Menu> getDmenus() {
        return dmenus;
    }

    public void setDmenus(List<Menu> dmenus) {
        this.dmenus = dmenus;
    }

    /**
     * 子菜单
     */
    private List<Menu> dmenus;

    public Integer getpMenuId() {
        return pMenuId;
    }

    public void setpMenuId(Integer pMenuId) {
        this.pMenuId = pMenuId;
    }

    private Integer pMenuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmenu.MENU_ID
     *
     * @mbggenerated
     */
    private Integer menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmenu.MENU_PAGE_URL
     *
     * @mbggenerated
     */
    private String menuPageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmenu.MENU_NAME
     *
     * @mbggenerated
     */
    private String menuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmenu.CTRL_CLASS
     *
     * @mbggenerated
     */
    private String ctrlClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmenu.CTRL_METHOD
     *
     * @mbggenerated
     */
    private String ctrlMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmenu.MENU_LEVEL
     *
     * @mbggenerated
     */
    private String menuLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmenu.MENU_STATUS
     *
     * @mbggenerated
     */
    private String menuStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmenu.MENU_ORDERBY
     *
     * @mbggenerated
     */
    private String menuOrderby;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmenu.MENU_ID
     *
     * @return the value of tmenu.MENU_ID
     *
     * @mbggenerated
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmenu.MENU_ID
     *
     * @param menuId the value for tmenu.MENU_ID
     *
     * @mbggenerated
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmenu.MENU_PAGE_URL
     *
     * @return the value of tmenu.MENU_PAGE_URL
     *
     * @mbggenerated
     */
    public String getMenuPageUrl() {
        return menuPageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmenu.MENU_PAGE_URL
     *
     * @param menuPageUrl the value for tmenu.MENU_PAGE_URL
     *
     * @mbggenerated
     */
    public void setMenuPageUrl(String menuPageUrl) {
        this.menuPageUrl = menuPageUrl == null ? null : menuPageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmenu.MENU_NAME
     *
     * @return the value of tmenu.MENU_NAME
     *
     * @mbggenerated
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmenu.MENU_NAME
     *
     * @param menuName the value for tmenu.MENU_NAME
     *
     * @mbggenerated
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName == null ? null : menuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmenu.CTRL_CLASS
     *
     * @return the value of tmenu.CTRL_CLASS
     *
     * @mbggenerated
     */
    public String getCtrlClass() {
        return ctrlClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmenu.CTRL_CLASS
     *
     * @param ctrlClass the value for tmenu.CTRL_CLASS
     *
     * @mbggenerated
     */
    public void setCtrlClass(String ctrlClass) {
        this.ctrlClass = ctrlClass == null ? null : ctrlClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmenu.CTRL_METHOD
     *
     * @return the value of tmenu.CTRL_METHOD
     *
     * @mbggenerated
     */
    public String getCtrlMethod() {
        return ctrlMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmenu.CTRL_METHOD
     *
     * @param ctrlMethod the value for tmenu.CTRL_METHOD
     *
     * @mbggenerated
     */
    public void setCtrlMethod(String ctrlMethod) {
        this.ctrlMethod = ctrlMethod == null ? null : ctrlMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmenu.MENU_LEVEL
     *
     * @return the value of tmenu.MENU_LEVEL
     *
     * @mbggenerated
     */
    public String getMenuLevel() {
        return menuLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmenu.MENU_LEVEL
     *
     * @param menuLevel the value for tmenu.MENU_LEVEL
     *
     * @mbggenerated
     */
    public void setMenuLevel(String menuLevel) {
        this.menuLevel = menuLevel == null ? null : menuLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmenu.MENU_STATUS
     *
     * @return the value of tmenu.MENU_STATUS
     *
     * @mbggenerated
     */
    public String getMenuStatus() {
        return menuStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmenu.MENU_STATUS
     *
     * @param menuStatus the value for tmenu.MENU_STATUS
     *
     * @mbggenerated
     */
    public void setMenuStatus(String menuStatus) {
        this.menuStatus = menuStatus == null ? null : menuStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmenu.MENU_ORDERBY
     *
     * @return the value of tmenu.MENU_ORDERBY
     *
     * @mbggenerated
     */
    public String getMenuOrderby() {
        return menuOrderby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmenu.MENU_ORDERBY
     *
     * @param menuOrderby the value for tmenu.MENU_ORDERBY
     *
     * @mbggenerated
     */
    public void setMenuOrderby(String menuOrderby) {
        this.menuOrderby = menuOrderby == null ? null : menuOrderby.trim();
    }
}